# Generated by Django 3.2.9 on 2021-12-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animaltype',
            old_name='name',
            new_name='clases',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='sity',
            new_name='city',
        ),
    ]
