# Generated by Django 3.2.9 on 2021-12-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_type',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Breed of animal'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type of animal'),
        ),
    ]
