# Generated by Django 3.2.9 on 2021-12-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20211208_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_type',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Breed of animal'),
        ),
    ]
