# Generated by Django 3.2.9 on 2021-12-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20211214_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='clases',
            field=models.CharField(choices=[('CAT', 'cat'), ('DOG', 'dog')], max_length=50, verbose_name='Type of animal'),
        ),
    ]
