# Generated by Django 3.2.9 on 2021-12-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_animaltype_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='clases',
            field=models.CharField(max_length=50, verbose_name='Type of animal'),
        ),
    ]
