# Generated by Django 3.2.9 on 2021-12-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_details_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details_type',
            name='name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.type', verbose_name='Type of animal'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Type of animal'),
        ),
    ]
