# Generated by Django 3.2.9 on 2021-12-08 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20211208_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='details_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.details_type', verbose_name='Type of animal'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='animal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.animal', verbose_name='animal information'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.location', verbose_name='find place'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='name of author'),
        ),
    ]
